### ISSUE TITLE
Update LESS

### ISSUE THREAD

**Issue by tophf** [openstyles/less-bundle#5]
%subj%

**Comment by eight04** [comment]
BTW, why did we build the browser bundle by our own?

**Comment by tophf** [comment]
I don't know but probably because our bundle is smaller. For 3.9.0 it's 131KB vs 163KB.

**Comment by eight04** [comment]
I tried to upgrade less to the latest version. The result has the same size as the official build because the package hosted on npm includes many interop for typescript/ESM.

Then I tried to build less from source, but then I found [a bug](https://github.com/less/less.js/issues/3591) that prevents the code from working. The result is around 130KB although it is unusable.

**Comment by tophf** [comment]
That bug is fixed now.
We also need its sourcemap generator to report correct positions.
